---
title: 'Temperature modelling: Exploratory analysis'
author: "Carles Milà"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', 
                      message = F, warnings = F, echo = F)

library("targets")
library("tidyverse")
library("lubridate")
library("colorspace")
library("knitr")
library("ggcorrplot")
library("lares")
```

```{r read data}
tar_load("temp_moddata")
tempdata <- read_csv(temp_moddata) %>%
  mutate(year = year(date))
```

# Missing values

```{r missingvals}
missingvals <- sapply(tempdata, function(x) tapply(x,  tempdata$year, function(y) sum(is.na(y))))
missingvals <- t(missingvals)
kable(missingvals)
tempdata <- tempdata[complete.cases(tempdata),]
```

# Correlation matrix

```{r cormat, fig.height=11, fig.width=10}
cont_temp <- dplyr::select_if(tempdata, is.numeric) %>%
  dplyr::select(-year, -julian)
cormat <- cor(cont_temp, method="spearman")
ggcorrplot(cormat, outline.col = "white", lab = F, hc.order=T,
           type = "upper", title="Spearman correlation matrix") +
  theme(legend.position = "none")
```

# Correlation rank

```{r top15}
corr_var(dplyr::select(tempdata, -year), tavg, method = "spearman", top = 15) 
```
