---
title: "OMI imputation: Results"
author: "Carles Milà"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', fig.width = 9, 
                      fig.height = 6, message = F, warnings = F, echo = F)

library("stars")
library("tidyverse")
library("colorspace")
library("knitr")
library("targets")
set.seed(1234)

tar_load("cat")
cat <- read_rds(cat)
```

## Model performance

```{r model performance}
quality_files <- list.files("outputs/omi_imp", "*.csv", full.names = T)
quality_files <- quality_files[grepl("modomi", quality_files)]
quality_files <- map_df(quality_files, read_csv) %>%
  pivot_wider(names_from = "method", values_from = c("rmse", "r2"))
kable(quality_files, digits=3)
```

## Variable importance

```{r varimp}
read_varimp <- function(pollutant, year){
  vimp <- read_csv(paste0("outputs/omi_imp/varimpomi_", pollutant, "_", year, ".csv"))
  vimp$Pollutant <- pollutant
  vimp$Year <- year
  vimp
}
varimp <- bind_rows(read_varimp("no2", "2018"), read_varimp("o3", "2018"),
                    read_varimp("no2", "2019"), read_varimp("o3", "2019"),
                    read_varimp("no2", "2020"), read_varimp("o3", "2020"))
                    
ggplot(varimp, aes(x=rowname, y=Overall, color=Year, fill=Year)) +
  geom_col(position = "dodge2", alpha = 0.1) +
  facet_wrap(~Pollutant, scales = "free_y") + 
  scale_fill_discrete_qualitative(palette = "Cold") +
  scale_colour_discrete_qualitative(palette = "Cold") +
  theme_light() +
  ylab("Variable importance (scaled to 0-100)") + xlab("Variable") +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank(), 
    legend.position = "bottom")
```

## NO2

### 2018

```{r no2 2018}
# Read original and imputed data
original <- read_rds("database/original/2018/omi_no2.rds")
imputed <- read_rds("outputs/omi_imp/impomi_no2_2018.rds")

# Draw a sample of 4 images
imgs <- sample(1:length(st_get_dimension_values(original, 3)), 4)
plotdata <- c(original[,,,imgs], imputed[,,,imgs], along=4) %>%
  st_set_dimensions(4, names="product", values = c("original", "imputed"))
plotdata <- st_crop(plotdata, cat)

# Plot
ggplot() +
  geom_stars(data=plotdata) +
  facet_grid(product ~ date) +
  scale_fill_viridis_c(na.value = "#FFFFFF00") +
  theme_bw() +
  theme(legend.position = "bottom", axis.text = element_blank(),
        axis.ticks = element_blank(), aspect.ratio=1, panel.grid=element_blank()) +
  labs(x="", y="", fill = "NO2", title = "OMI NO2 imputation for 4 random days") 
```

### 2019

```{r no2 2019}
# Read original and imputed data
original <- read_rds("database/original/2019/omi_no2.rds")
imputed <- read_rds("outputs/omi_imp/impomi_no2_2019.rds")

# Draw a sample of 4 images
imgs <- sample(1:length(st_get_dimension_values(original, 3)), 4)
plotdata <- c(original[,,,imgs], imputed[,,,imgs], along=4) %>%
  st_set_dimensions(4, names="product", values = c("original", "imputed"))
plotdata <- st_crop(plotdata, cat)

# Plot
ggplot() +
  geom_stars(data=plotdata) +
  facet_grid(product ~ date) +
  scale_fill_viridis_c(na.value = "#FFFFFF00") +
  theme_bw() +
  theme(legend.position = "bottom", axis.text = element_blank(),
        axis.ticks = element_blank(), aspect.ratio=1, panel.grid=element_blank()) +
  labs(x="", y="", fill = "NO2", title = "OMI NO2 imputation for 4 random days") 
```

### 2020

```{r no2 2020}
# Read original and imputed data
original <- read_rds("database/original/2020/omi_no2.rds")
imputed <- read_rds("outputs/omi_imp/impomi_no2_2020.rds")

# Draw a sample of 4 images
imgs <- sample(1:length(st_get_dimension_values(original, 3)), 4)
plotdata <- c(original[,,,imgs], imputed[,,,imgs], along=4) %>%
  st_set_dimensions(4, names="product", values = c("original", "imputed"))
plotdata <- st_crop(plotdata, cat)

# Plot
ggplot() +
  geom_stars(data=plotdata) +
  facet_grid(product ~ date) +
  scale_fill_viridis_c(na.value = "#FFFFFF00") +
  theme_bw() +
  theme(legend.position = "bottom", axis.text = element_blank(),
        axis.ticks = element_blank(), aspect.ratio=1, panel.grid=element_blank()) +
  labs(x="", y="", fill = "NO2", title = "OMI NO2 imputation for 4 random days") 
```

## O3

### 2018

```{r o3 2018}
# Read original and imputed data
original <- read_rds("database/original/2018/omi_o3.rds")
imputed <- read_rds("outputs/omi_imp/impomi_o3_2018.rds")

# Draw a sample of 4 images
imgs <- sample(1:length(st_get_dimension_values(original, 3)), 4)
plotdata <- c(original[,,,imgs], imputed[,,,imgs], along=4) %>%
  st_set_dimensions(4, names="product", values = c("original", "imputed"))
plotdata <- st_crop(plotdata, cat)

# Plot
ggplot() +
  geom_stars(data=plotdata) +
  facet_grid(product ~ date) +
  scale_fill_viridis_c(na.value = "#FFFFFF00") +
  theme_bw() +
  theme(legend.position = "bottom", axis.text = element_blank(),
        axis.ticks = element_blank(), aspect.ratio=1, panel.grid=element_blank()) +
  labs(x="", y="", fill = "O3", title = "OMI O3 imputation for 4 random days") 
```

### 2019

```{r o3 2019}
# Read original and imputed data
original <- read_rds("database/original/2019/omi_o3.rds")
imputed <- read_rds("outputs/omi_imp/impomi_o3_2019.rds")

# Draw a sample of 4 images
imgs <- sample(1:length(st_get_dimension_values(original, 3)), 4)
plotdata <- c(original[,,,imgs], imputed[,,,imgs], along=4) %>%
  st_set_dimensions(4, names="product", values = c("original", "imputed"))
plotdata <- st_crop(plotdata, cat)

# Plot
ggplot() +
  geom_stars(data=plotdata) +
  facet_grid(product ~ date) +
  scale_fill_viridis_c(na.value = "#FFFFFF00") +
  theme_bw() +
  theme(legend.position = "bottom", axis.text = element_blank(),
        axis.ticks = element_blank(), aspect.ratio=1, panel.grid=element_blank()) +
  labs(x="", y="", fill = "O3", title = "OMI O3 imputation for 4 random days") 
```

### 2020

```{r o3 2020}
# Read original and imputed data
original <- read_rds("database/original/2020/omi_o3.rds")
imputed <- read_rds("outputs/omi_imp/impomi_o3_2020.rds")

# Draw a sample of 4 images
imgs <- sample(1:length(st_get_dimension_values(original, 3)), 4)
plotdata <- c(original[,,,imgs], imputed[,,,imgs], along=4) %>%
  st_set_dimensions(4, names="product", values = c("original", "imputed"))
plotdata <- st_crop(plotdata, cat)

# Plot
ggplot() +
  geom_stars(data=plotdata) +
  facet_grid(product ~ date) +
  scale_fill_viridis_c(na.value = "#FFFFFF00") +
  theme_bw() +
  theme(legend.position = "bottom", axis.text = element_blank(),
        axis.ticks = element_blank(), aspect.ratio=1, panel.grid=element_blank()) +
  labs(x="", y="", fill = "O3", title = "OMI O3 imputation for 4 random days") 
```
