---
title: "TROPOMI imputation: Exploratory analysis"
author: "Carles Milà"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', 
                      message = F, warnings = F, echo = F)

library("targets")
library("tidyverse")
library("viridis")
library("RColorBrewer")
library("ggcorrplot")
library("lares")
```

## NO2 

### Correlation matrix of predictors: 2019

```{r cormat no2, fig.height=8, fig.width=9}
tar_load("tropomi_train")
tropo_train <- read_csv(gsub("year", "2019", tropomi_train$tropomi_no2)) %>%
  dplyr::filter(split=="train") %>%
  dplyr::select(-split)
set.seed(1234)
isamples <- sample(1:nrow(tropo_train), 100000)
tropo_train <- tropo_train[isamples,]
tropo_train <- dplyr::select(tropo_train, where(is.numeric))
cormat <- cor(tropo_train, method="spearman")
ggcorrplot(cormat, hc.order = TRUE, outline.col = "white", 
           title="Spearman correlation matrix (100000 random samples)")
```

### Correlation rank: 2020

```{r corrank no2}
corr_var(tropo_train, tropo_no2, method = "spearman", top = 10) 
rm("tropo_train")
```


## O3 

### Correlation matrix of predictors: 2019

```{r cormat o3, fig.height=8, fig.width=9}
tar_load("tropomi_train")
tropo_train <- read_csv(gsub("year", "2019", tropomi_train$tropomi_o3)) %>%
  dplyr::filter(split=="train") %>%
  dplyr::select(-split)
set.seed(1234)
isamples <- sample(1:nrow(tropo_train), 100000)
tropo_train <- tropo_train[isamples,]
tropo_train <- dplyr::select(tropo_train, where(is.numeric))
cormat <- cor(tropo_train, method="spearman")
ggcorrplot(cormat, hc.order = TRUE, outline.col = "white", 
           title="Spearman correlation matrix (100000 random samples)")
```

### Correlation rank: 2020

```{r corrank o3}
corr_var(tropo_train, tropo_o3, method = "spearman", top = 10) 
rm("tropo_train")
```
